thresholds:
  memory_pressure_percent: 80 #flag is true if memory usage is over this value
  cpu_saturation_percent: 20 #flag is true if idle cpu is below saturation

windows: 
  default: [5, 15]
